#!/bin/bash
# Auto-generated by sboxd — last product claude invocation.
# Run this script to resume the session interactively.
exec node -e '
const fs = require("fs");
const {spawn} = require("child_process");
const {argv, env, cwd} = JSON.parse(fs.readFileSync("/workspaces/default/code/.claude-replay.json", "utf8"));
const e = {};
for (const entry of env) { const i = entry.indexOf("="); if (i > 0) e[entry.slice(0,i)] = entry.slice(i+1); }
const child = spawn(argv[0], argv.slice(1), {stdio:"inherit", env: e, cwd});
child.on("exit", (code) => process.exit(code || 0));
'
